version: "3.7"
services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      -db
  db:
    dialect: postgres
    container_name: employee-rest-api
    image: postgres:10.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cf090303
      POSTGRES_DB: Mavericks
    ports: 
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
volumes:
  db-data